### PR TITLE
Add the method that devides tablets or others

### PR DESCRIPTION
**Pull request by hiratai**
I add the method that returns whether the device is tablet.

It's not a new algorithm. 
You can write like
 `request.tablet?`
instead of
 `request.mobile and request.mobile.tablet?`

It's simple.

### CODE REVIEW

**Comment by rust** [comment]
Thank you for your corporation!

Please update the document about this method, if possible.

**Comment by hiratai** [comment]
added a simple description to the document for this method :)

**Comment by rust** [comment]
:+1:

**Comment by hiratai** [comment]
Thank you :->

**Pull request merged**
